spring:
  activemq:
#    broker-url: tcp://localhost:61616
    broker-url: vm://embedded?broker.persistent=false
    in-memory: true
    non-blocking-redelivery: true

queue:
  task: runtask.q

#logging:
#  level:
#    ROOT: DEBUG
