spring:
  activemq:
    broker-url: tcp://localhost:61616
    in-memory: true
    non-blocking-redelivery: true

serverqueue:
  outbound: outbound.queue
  inbound: inbound.queue

#logging:
#  level:
#    ROOT: DEBUG
