spring:
  activemq:
    broker-url: tcp://localhost:61616

serverqueue:
  outbound: outbound.queue
  inbound: inbound.queue

worker:
  current-node-number: ${random.int[100,999]}


#logging:
#  level:
#    ROOT: DEBUG